spring:
  config:
    activate:
      on-profile: mtls

  ssl:
    bundle:
      pem:
        mtls-server:
          keystore:
            certificate: ${MTLS_SERVER_CERT_PATH}
            private-key: ${MTLS_SERVER_KEY_PATH}
          truststore:
            certificate: ${MTLS_CA_CERT_PATH}

server:
  ssl:
    enabled: true
    bundle: mtls-server
    client-auth: need

grpc:
  client:
    user-group-service:
      negotiation-type: TLS
      security:
        client-auth-enabled: true
        trust-cert-collection: ${GRPC_CLIENT_TRUST_CERT_COLLECTION_PATH:${MTLS_CA_CERT_PATH}}
        certificate-chain: ${GRPC_CLIENT_CERT_CHAIN_PATH:${MTLS_SERVER_CERT_PATH}}
        private-key: ${GRPC_CLIENT_PRIVATE_KEY_PATH:${MTLS_SERVER_KEY_PATH}}
        authority-override: ${GRPC_USERGROUP_AUTHORITY_OVERRIDE:user-group-service}
