import fs from 'node:fs/promises';
import path from 'node:path';
import dotenv from 'dotenv';
import yaml from 'js-yaml';

dotenv.config({ path: path.resolve('.env.test') });

const baseUrl = process.env.BASE_URL || 'http://localhost:9080';
const identityDocsUrl = process.env.IDENTITY_DOCS_URL || 'http://localhost:8081/v3/api-docs';
const userGroupDocsUrl = process.env.USER_GROUP_DOCS_URL || 'http://localhost:8082/v3/api-docs';
const projectConfigDocsUrl = process.env.PROJECT_CONFIG_DOCS_URL || 'http://localhost:8084/v3/api-docs';

const sources = [
  { key: 'identity', url: identityDocsUrl },
  { key: 'userGroup', url: userGroupDocsUrl },
  { key: 'projectConfig', url: projectConfigDocsUrl }
];

const componentBuckets = [
  'schemas',
  'responses',
  'parameters',
  'examples',
  'requestBodies',
  'headers',
  'securitySchemes',
  'links',
  'callbacks'
];

function rewriteRefs(obj, keyPrefix, componentRenameMap) {
  if (obj === null || obj === undefined) return obj;
  if (Array.isArray(obj)) return obj.map((it) => rewriteRefs(it, keyPrefix, componentRenameMap));
  if (typeof obj !== 'object') return obj;

  const out = {};
  for (const [k, v] of Object.entries(obj)) {
    if (k === '$ref' && typeof v === 'string' && v.startsWith('#/components/')) {
      const parts = v.split('/');
      const bucket = parts[2];
      const oldName = parts[3];
      const mapped = componentRenameMap[bucket]?.[oldName] || `${keyPrefix}_${oldName}`;
      out[k] = `#/components/${bucket}/${mapped}`;
    } else {
      out[k] = rewriteRefs(v, keyPrefix, componentRenameMap);
    }
  }
  return out;
}

function ensureErrorContract(doc) {
  doc.components = doc.components || {};
  doc.components.schemas = doc.components.schemas || {};
  doc.components.responses = doc.components.responses || {};
  doc.components.schemas.StandardError = {
    type: 'object',
    properties: {
      statusCode: { type: 'integer', example: 400 },
      error: {
        oneOf: [
          { type: 'string', example: 'Bad Request' },
          {
            type: 'object',
            properties: {
              code: { type: 'integer', example: 401 },
              message: { type: 'string', example: 'Unauthorized' }
            }
          }
        ]
      },
      message: { type: 'string', example: 'Invalid UUID' },
      timestamp: { type: 'string', format: 'date-time' }
    }
  };

  const statuses = [400, 401, 403, 404, 409, 500];
  for (const status of statuses) {
    const name = `Error${status}`;
    doc.components.responses[name] = {
      description: `${status} error`,
      content: {
        'application/json': {
          schema: { $ref: '#/components/schemas/StandardError' }
        }
      }
    };
  }
}

function ensurePathParameters(doc) {
  for (const [pathKey, pathItem] of Object.entries(doc.paths || {})) {
    const matches = [...pathKey.matchAll(/\{([^}]+)\}/g)].map((m) => m[1]);
    if (matches.length === 0) continue;

    for (const [method, operation] of Object.entries(pathItem || {})) {
      if (!operation || typeof operation !== 'object') continue;
      if (!['get', 'post', 'put', 'patch', 'delete', 'options', 'head'].includes(method)) continue;

      operation.parameters = Array.isArray(operation.parameters) ? operation.parameters : [];
      for (const paramName of matches) {
        const exists = operation.parameters.some((p) => p && p.in === 'path' && p.name === paramName);
        if (!exists) {
          operation.parameters.push({
            name: paramName,
            in: 'path',
            required: true,
            schema: { type: 'string' }
          });
        }
      }
    }
  }
}

async function fetchJson(url) {
  const resp = await fetch(url, { headers: { Accept: 'application/json' } });
  if (!resp.ok) {
    throw new Error(`Failed ${url}: ${resp.status} ${resp.statusText}`);
  }
  return resp.json();
}

async function main() {
  const unified = {
    openapi: '3.0.3',
    info: {
      title: 'SAMT Unified Backend API',
      version: '1.0.0',
      description: 'Generated by scripts/generate-openapi.mjs from service OpenAPI docs exposed via API Gateway.'
    },
    servers: [{ url: baseUrl }],
    tags: [],
    paths: {},
    components: {
      schemas: {},
      responses: {},
      parameters: {},
      examples: {},
      requestBodies: {},
      headers: {},
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT'
        }
      },
      links: {},
      callbacks: {}
    }
  };

  const errors = [];

  for (const src of sources) {
    try {
      const raw = await fetchJson(src.url);
      const componentRenameMap = {};
      const converted = rewriteRefs(raw, src.key, componentRenameMap);

      const rawComponents = raw.components || {};
      for (const bucket of componentBuckets) {
        const values = rawComponents[bucket] || {};
        if (!componentRenameMap[bucket]) componentRenameMap[bucket] = {};

        for (const [name, value] of Object.entries(values)) {
          const newName = `${src.key}_${name}`;
          componentRenameMap[bucket][name] = newName;
          unified.components[bucket][newName] = rewriteRefs(value, src.key, componentRenameMap);
        }
      }

      const pathsObj = converted.paths || {};
      for (const [p, methods] of Object.entries(pathsObj)) {
        unified.paths[p] = unified.paths[p] || {};
        for (const [method, operation] of Object.entries(methods)) {
          const op = { ...operation };
          if (!op.tags || op.tags.length === 0) {
            op.tags = [src.key];
          }
          if (!op.responses) op.responses = {};
          for (const status of ['400', '401', '403', '404', '409', '500']) {
            op.responses[status] = op.responses[status] || { $ref: `#/components/responses/Error${status}` };
          }
          unified.paths[p][method] = op;
        }
      }

      unified.tags.push({ name: src.key, description: `Operations proxied from ${src.key} service` });
      console.log(`Loaded OpenAPI source: ${src.url}`);
    } catch (err) {
      errors.push(String(err.message || err));
      console.warn(`Skipping source ${src.url}: ${err.message}`);
    }
  }

  ensureErrorContract(unified);
  ensurePathParameters(unified);

  if (Object.keys(unified.paths).length === 0) {
    throw new Error(
      `No OpenAPI sources were reachable from ${baseUrl}. Ensure backend is running and gateway exposes /identity, /user-group, /project-config docs.`
    );
  }

  const yamlOutput = yaml.dump(unified, {
    lineWidth: 140,
    noRefs: true,
    sortKeys: false
  });

  await fs.writeFile(path.resolve('openapi.yaml'), yamlOutput, 'utf8');
  console.log(`openapi.yaml generated with ${Object.keys(unified.paths).length} paths.`);

  if (errors.length > 0) {
    console.log('Completed with partial sources:');
    for (const e of errors) console.log(`- ${e}`);
  }
}

main().catch((err) => {
  console.error(err.message || err);
  process.exit(1);
});
